export const districts = [
    "Karachi Central",
    "Karachi East",
    "Karachi South",
    "Karachi West",
    "Korangi",
    "Malir",
    "Keamari",
    "Hyderabad",
    "Tando Allahyar",
    "Tando Muhammad Khan",
    "Matiari",
    "Jamshoro",
    "Sukkur",
    "Ghotki",
    "Khairpur",
    "Naushahro Feroze",
    "Larkana",
    "Kamber-Shahdadkot",
    "Shikarpur",
    "Jacobabad",
    "Kashmore-Kandhkot",
    "Shaheed Benazirabad",
    "Sanghar",
    "Mirpur Khas",
    "Umerkot",
    "Tharparkar",
    "Sujawal",
    "Thatta",
    "Badin",
    "Dadu"
  ];